---
platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/fedora, tag: build}

run:
  path: ci/build.sh
    
inputs:
  - name: glibc-ci
    path: ci

outputs:
  - name: glibc
    path: out
  
